### PR TITLE
Version for API 1.6.0 or 1.8.0 and Eiger1 or Eiger2

### PR DESCRIPTION
**Pull request by MarkRivers**
This PR is based on the work by Gary Yandel at DLS, with some improvements.

- It does not assume that the Eiger1 runs the Simplon API 1.6.0 and the Eiger2 runs 1.8.0.  There are now some Eiger1 detectors running 1.8.0.  The driver thus knows both what version of the Simplon API the detector uses as well as what Eiger model it is.
- The eigerDetectorConfig command does not take the eigerModel argument that the DLS branch used.  The driver determines both the Simplon API in use and the Eiger model via the Simplon API.
- It is been tested with an Eiger1 500K and an Eiger2 500K.

There is still additional work to be done:
- Add support for additional Eiger2 features, such as 2 energy thresholds, number of exposures per image, etc.
- Make medm screens that are model/API specific.
- More testing

Since this version appears to work with both APIs and both models it can be merged into master while additional work is done on another branch.

### CODE REVIEW

**Comment by cmkewish** [comment]
Hi @MarkRivers 

An issue I ran into was the EIGER2 X 1M detector failing to correctly disarm when trying to interrupt a running series of exposures.

We run a mode that we call "freerun" scans where we set (in the API language) the trigger mode to manually-triggered internal series, with `ntriggers` = 1 and, e.g., `nimages` = 2 * [number of expected pixels needed in a scan], and then let the detector time it's own acquisitions, and send a `disarm` at the end to close the series. The master file ends up containing a ton of empty data links at the end but this is fine.

This was working prior to 2020.1 (I think) but when I asked Dectris about it they suggested to add a `cancel` or an `abort` command before `disarm`? The first one will stop the data acquisition after the current image is completed, while the second command would stop any acquisition immediately.

Is it included (or possible to include) into this ADEiger version to send CANCEL then DISARM when issuing a Acquire=0?

Thanks,
Cameron

**Comment by MarkRivers** [comment]
@cmkewish I have created a new issue #39 for your problem, separating it from this PR.

**Comment by MarkRivers** [comment]
@MarkRivers said:
>There is still additional work to be done:
Add support for additional Eiger2 features, such as 2 energy thresholds, number of exposures per image, etc.
Make medm screens that are model/API specific.
More testing

I have now added support for 2 energy thresholds, and I have model-specific medm screens and auto-converted OPI screens.

I have also added support for ExternalGate feature that will be in the next firmware release in early 2021 but is already available for testing.

I just tagged R2-7 which had all changes prior to adding Eiger2 support.

I think this branch is now working well enough to be merged into master, so I am doing that now.

**Comment by MarkRivers** [comment]
I am close to being ready to tag a new release.  I would appreciate if people can test the master branch on both Eiger1 and Eiger2 detectors.  Remaining things to be done:
- Check if reordering the enums is necessary any more.  It seems like it may have been a problem in 2020.1 firmware but fixed in 2020.2.
-  Try to turn off acquisition in External Series and External Enable mode when the requested number of frames have been received in the Stream interface. (see #28)
- Try to fix issue #39

**Pull request merged**
