### PR TITLE
WIP: 1.8

### PR DESCRIPTION
**Pull request by GDYendell**
This is a WIP branch for review of the new 1.8 API for Eiger2.

There are still some outstanding issues: 

- Many parameters are still missing, which may or may not be added back in
- Some of the existing parameters do not have access_mode, so it currently assumes they are RW
- The detectors have been so unstable that I added the ability to re-initialize at runtime, which maybe shouldn't stay in
- The initialization time has been increased a lot because it takes so long, I am not sure if this will be fixed
- status_update has been removed

In any case, anything that is currently commented out should either be added back in or removed properly before this is merged.

In terms of improvements, there are some new parameters and some improved logic.

### CODE REVIEW

**Comment by cmkewish** [comment]
Currently, if I try to interact with the Monitor interface using the MEDM window, or:
`caput SR05ID01EIG1:cam1:MonitorEnable 1`
the IOC crashes.

```
$ caget SR05ID01EIG1:cam1:MonitorEnable
SR05ID01EIG1:cam1:MonitorEnable No
$ caput SR05ID01EIG1:cam1:MonitorEnable 0
Old : SR05ID01EIG1:cam1:MonitorEnable No
New : SR05ID01EIG1:cam1:MonitorEnable No
$ caput SR05ID01EIG1:cam1:MonitorEnable 1
Old : SR05ID01EIG1:cam1:MonitorEnable No
New : SR05ID01EIG1:cam1:MonitorEnable Yes
```
<details><summary>Crash backtrace from EPICS, click to expand...</summary><p>
```
epics> *** Error in `../../bin/linux-x86_64/eigerDetectorApp': free(): invalid next size (fast): 0x00007f4474002cd0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7f44dd815619]
../../bin/linux-x86_64/eigerDetectorApp[0x4266db]
../../bin/linux-x86_64/eigerDetectorApp[0x4267e9]
../../bin/linux-x86_64/eigerDetectorApp[0x41d030]
../../bin/linux-x86_64/eigerDetectorApp[0xed1b6f]
/lib64/libpthread.so.0(+0x7e25)[0x7f44de9d5e25]
/lib64/libc.so.6(clone+0x6d)[0x7f44dd89134d]
======= Memory map: ========
00400000-011b6000 r-xp 00000000 fd:00 26626884                           /beamline/epics/support/areaDetector/ADEiger/iocs/eigerIOC/bin/linux-x86_64/eigerDetectorApp
013b6000-01434000 r--p 00db6000 fd:00 26626884                           /beamline/epics/support/areaDetector/ADEiger/iocs/eigerIOC/bin/linux-x86_64/eigerDetectorApp
01434000-01473000 rw-p 00e34000 fd:00 26626884                           /beamline/epics/support/areaDetector/ADEiger/iocs/eigerIOC/bin/linux-x86_64/eigerDetectorApp
01473000-014b6000 rw-p 00000000 00:00 0 
02c4b000-02f84000 rw-p 00000000 00:00 0                                  [heap]
7f4450000000-7f4450021000 rw-p 00000000 00:00 0 
7f4450021000-7f4454000000 ---p 00000000 00:00 0 
7f4454000000-7f4454021000 rw-p 00000000 00:00 0 
7f4454021000-7f4458000000 ---p 00000000 00:00 0 
7f4458000000-7f4458027000 rw-p 00000000 00:00 0 
7f4458027000-7f445c000000 ---p 00000000 00:00 0 
7f445dad7000-7f4464000000 r--p 00000000 fd:00 8776672                    /usr/lib/locale/locale-archive
7f4464000000-7f4464021000 rw-p 00000000 00:00 0 
7f4464021000-7f4468000000 ---p 00000000 00:00 0 
7f4468000000-7f4468021000 rw-p 00000000 00:00 0 
7f4468021000-7f446c000000 ---p 00000000 00:00 0 
7f446c000000-7f446c022000 rw-p 00000000 00:00 0 
7f446c022000-7f4470000000 ---p 00000000 00:00 0 
7f4470000000-7f4470021000 rw-p 00000000 00:00 0 
7f4470021000-7f4474000000 ---p 00000000 00:00 0 
7f4474000000-7f4474021000 rw-p 00000000 00:00 0 
7f4474021000-7f4478000000 ---p 00000000 00:00 0 
7f4478000000-7f4478021000 rw-p 00000000 00:00 0 
7f4478021000-7f447c000000 ---p 00000000 00:00 0 
7f447c000000-7f447c021000 rw-p 00000000 00:00 0 
7f447c021000-7f4480000000 ---p 00000000 00:00 0 
7f4480000000-7f4480021000 rw-p 00000000 00:00 0 
7f4480021000-7f4484000000 ---p 00000000 00:00 0 
7f4484000000-7f4484021000 rw-p 00000000 00:00 0 
7f4484021000-7f4488000000 ---p 00000000 00:00 0 
7f448a65e000-7f448a65f000 ---p 00000000 00:00 0 
7f448a65f000-7f448a85f000 rw-p 00000000 00:00 0 
7f448a85f000-7f448a860000 ---p 00000000 00:00 0 
7f448a860000-7f448a960000 rw-p 00000000 00:00 0 
7f448a960000-7f448a961000 ---p 00000000 00:00 0 
7f448a961000-7f448ab61000 rw-p 00000000 00:00 0                          [stack:1088]
7f448ab61000-7f448ab62000 ---p 00000000 00:00 0 
7f448ab62000-7f448ad62000 rw-p 00000000 00:00 0                          [stack:1079]
7f448ad62000-7f448ad63000 ---p 00000000 00:00 0 
7f448ad63000-7f448af63000 rw-p 00000000 00:00 0                          [stack:1074]
7f448af63000-7f448af64000 ---p 00000000 00:00 0 
7f448af64000-7f448b064000 rw-p 00000000 00:00 0                          [stack:1070]
7f448b064000-7f448b065000 ---p 00000000 00:00 0 
7f448b065000-7f448b165000 rw-p 00000000 00:00 0                          [stack:1069]
7f448b165000-7f448b171000 r-xp 00000000 fd:00 60999                      /usr/lib64/libnss_files-2.17.so
7f448b171000-7f448b370000 ---p 0000c000 fd:00 60999                      /usr/lib64/libnss_files-2.17.so
7f448b370000-7f448b371000 r--p 0000b000 fd:00 60999                      /usr/lib64/libnss_files-2.17.so
7f448b371000-7f448b372000 rw-p 0000c000 fd:00 60999                      /usr/lib64/libnss_files-2.17.so
7f448b372000-7f448b378000 rw-p 00000000 00:00 0 
7f448b378000-7f448b379000 ---p 00000000 00:00 0 
7f448b379000-7f448b479000 rw-p 00000000 00:00 0                          [stack:1068]
7f448b479000-7f448b47a000 ---p 00000000 00:00 0 
7f448b47a000-7f448b67a000 rw-p 00000000 00:00 0                          [stack:1067]
7f448b67a000-7f448b67b000 ---p 00000000 00:00 0 
7f448b67b000-7f448b87b000 rw-p 00000000 00:00 0                          [stack:1066]
7f448b87b000-7f448b87c000 ---p 00000000 00:00 0 
7f448b87c000-7f448b97c000 rw-p 00000000 00:00 0                          [stack:1065]
7f448b97c000-7f448b97d000 ---p 00000000 00:00 0 
7f448b97d000-7f448b9fd000 rw-p 00000000 00:00 0                          [stack:1064]
7f448b9fd000-7f448b9fe000 ---p 00000000 00:00 0 
7f448b9fe000-7f448bbfe000 rw-p 00000000 00:00 0                          [stack:1057]
7f448bbfe000-7f448bbff000 ---p 00000000 00:00 0 
7f448bbff000-7f448bdff000 rw-p 00000000 00:00 0                          [stack:1056]
7f448bdff000-7f448be00000 ---p 00000000 00:00 0 
7f448be00000-7f448c000000 rw-p 00000000 00:00 0                          [stack:1055]
7f448c000000-7f448c021000 rw-p 00000000 00:00 0 
7f448c021000-7f4490000000 ---p 00000000 00:00 0 
7f4490000000-7f4490021000 rw-p 00000000 00:00 0 
7f4490021000-7f4494000000 ---p 00000000 00:00 0 
7f4494000000-7f4494021000 rw-p 00000000 00:00 0 
7f4494021000-7f4498000000 ---p 00000000 00:00 0 
7f4498000000-7f4498021000 rw-p 00000000 00:00 0 
7f4498021000-7f449c000000 ---p 00000000 00:00 0 
7f449c000000-7f449c054000 rw-p 00000000 00:00 0 
7f449c054000-7f44a0000000 ---p 00000000 00:00 0 
7f44a0000000-7f44a0021000 rw-p 00000000 00:00 0 
7f44a0021000-7f44a4000000 ---p 00000000 00:00 0 
7f44a4000000-7f44a4021000 rw-p 00000000 00:00 0 
7f44a4021000-7f44a8000000 ---p 00000000 00:00 0 
7f44a8000000-7f44a8021000 rw-p 00000000 00:00 0 
7f44a8021000-7f44ac000000 ---p 00000000 00:00 0 
7f44ac000000-7f44ac021000 rw-p 00000000 00:00 0 
7f44ac021000-7f44b0000000 ---p 00000000 00:00 0 
7f44b0000000-7f44b0021000 rw-p 00000000 00:00 0 
7f44b0021000-7f44b4000000 ---p 00000000 00:00 0 
7f44b4000000-7f44b4021000 rw-p 00000000 00:00 0 
7f44b4021000-7f44b8000000 ---p 00000000 00:00 0 
7f44b8000000-7f44b8021000 rw-p 00000000 00:00 0 
7f44b8021000-7f44bc000000 ---p 00000000 00:00 0 
7f44bc000000-7f44bc021000 rw-p 00000000 00:00 0 
7f44bc021000-7f44c0000000 ---p 00000000 00:00 0 
7f44c0000000-7f44c0021000 rw-p 00000000 00:00 0 
7f44c0021000-7f44c4000000 ---p 00000000 00:00 0 
7f44c4000000-7f44c4021000 rw-p 00000000 00:00 0 
7f44c4021000-7f44c8000000 ---p 00000000 00:00 0 
7f44c8000000-7f44c8021000 rw-p 00000000 00:00 0 
7f44c8021000-7f44cc000000 ---p 00000000 00:00 0 
7f44cc000000-7f44cc021000 rw-p 00000000 00:00 0 
7f44cc021000-7f44d0000000 ---p 00000000 00:00 0 
7f44d0000000-7f44d0021000 rw-p 00000000 00:00 0 
7f44d0021000-7f44d4000000 ---p 00000000 00:00 0 
7f44d4000000-7f44d4021000 rw-p 00000000 00:00 0 
7f44d4021000-7f44d8000000 ---p 00000000 00:00 0 
7f44d803f000-7f44d8080000 rw-p 00000000 00:00 0 
7f44d8080000-7f44d8081000 ---p 00000000 00:00 0 
7f44d8081000-7f44d8181000 rw-p 00000000 00:00 0                          [stack:1063]Aborted
```
</p></details>

Also: despite the above responses from `caget` and `caput`, currently the detector reports that 0 = enabled, 1 = disabled for this parameter, when I request in Firefox: `http://eigerip/monitor/api/1.8.0/config/mode`

image

**Comment by GDYendell** [comment]
I can reproduce this. The stack trace is:

```
raise 0x00007fc6028102c7
abort 0x00007fc6028119b8
__libc_message 0x00007fc602852e17
_int_free 0x00007fc60285b609
RestAPI::getBlob restApi.cpp:849
RestAPI::getMonitorImage restApi.cpp:480
eigerDetector::monitorTask eigerDetector.cpp:1182
start_routine osdThread.c:385
start_thread 0x00007fc6025c5dd5
clone 0x00007fc6028d802d
```

Those methods have not changed since Bruno's initial versions up to 2017.

We don't use the monitor stream much at DLS, but it was working (enabling the monitor without it crashing) on 1.8. I do know that Albula currently cannot view the monitor stream because it has changed. Looking at our old Eiger 1, the monitor/mode parameter API has not changed either.

**Comment by brunoseivam** [comment]
This wasn't being used much at BNL either, at the time. Note that ADEiger expects a TIFF image coming from the detector, and it does a very, *ahem*, artisanal parsing of the TIFF header for simplicity:

https://github.com/areaDetector/ADEiger/blob/d0dbd553c70624a847cda8b25a979acdebc1ae28/eigerApp/src/eigerDetector.cpp#L1538-L1614

**Comment by brunoseivam** [comment]
I am staring at the code, and everything seems correct. Unless the detector is sending a bogus Content Length?

https://github.com/areaDetector/ADEiger/blob/d0dbd553c70624a847cda8b25a979acdebc1ae28/eigerApp/src/restApi.cpp#L827

**Comment by GDYendell** [comment]
I think it might be trying to request images when the monitor stream isn't actually enabled on the detector. Debugging the code the response.contentLength is 0, so 

https://github.com/areaDetector/ADEiger/blob/d0dbd553c70624a847cda8b25a979acdebc1ae28/eigerApp/src/restApi.cpp#L840

evaluates to 18446744073709551266. But, I can't see why it doesn't handle that, because it just `recv`s until `received = 0` then calls `free(*buf)` and that fails.

**Comment by brunoseivam** [comment]
We should reject messages with Content Length = 0 and not let underflow happen like this. I am thinking that `malloc(0)` might be the culprit, but it should be safe:

```
       The malloc() function allocates size bytes and returns a pointer to the
       allocated memory.  The memory is not initialized.  If size is  0,  then
       malloc()  returns either NULL, or a unique pointer value that can later
       be successfully passed to free().

```

**Comment by jlmuir** [comment]
What's the status of this PR?  I'm planning to use the ADEiger driver to control an EIGER2 X 9M.  Should I use the master branch, or should I use this PR?

**Comment by cmkewish** [comment]
@jlmuir I am using this PR to populate PVs for controlling EIGER2 X 1M. I use ADEiger to configure the detector for acquisitions in EPICS, but I don't use any plugins or handle any data with it.

**Comment by MarkRivers** [comment]
> @jlmuir I am using this PR to populate PVs for controlling EIGER2 X 1M. I use ADEiger to configure the detector and start/stop acquisitions in EPICS, but I don't use any plugins or handle any data with it.

@cmkewish have you tried using the Stream interface to get data and see if plugins work, even if you are not using that in production?

**Comment by GDYendell** [comment]
We have been using this branch at DLS on multiple Eiger2 detectors for a few months now with no problems. We use the Stream interface, but not through the areaDetector plugin chain, as we have a separate file writer. I don't think at this point that there are any breaking changes to the stream API (there were with the initial versions of 1.8). If you integrate this branch it should work with Eiger2 detectors, but it will not work with Eiger1 detectors.

There is further work required to make ADEiger work happily with both so that his can be merged. I do have a local branch with some progress towards this, but the current state is that it doesn't work with either. I haven't pushed it here as then there would not be any Eiger2 solution available. We will be moving away from ADEiger at the beginning of next year, so our development effort on this has stalled.

I think @MarkRivers is visiting DLS next year, so that could be a good time to finalise this branch and get it merged.

**Comment by cmkewish** [comment]
> @cmkewish have you tried using the Stream interface to get data and see if plugins work, even if you are not using that in production?

@MarkRivers I haven't played around with it much, once able to read and write the EIGER2 PVs and configure and launch scans, I left things as they were. The default settings that I enable now at the beginning of each scan, clearly show workarounds in place that were put in to move our system from running with a prototype EIGER1 to the new EIGER2: CompressionAlgo=1, DataSource=0, WaitForPlugins=0 [... and MonitorEnable=1 is commented out due to the above discussion about crashing], and FWEnable=1. We use an external Python script to handle the transfer of HDF5 files from the DCU to appropriate locations in our beamline filesystem based on filename prefixes.

It could definitely use optimization: i have been meaning to experiment with the Stream interface, but time hasn't permitted.

**Comment by jlmuir** [comment]
Compiled against EPICS 3.15.7, when I try to run this with `st.cmd`, it fails to load `eiger.template` with the following error:

```
dbLoadRecords("/path/to/ADEiger/iocs/eigerIOC/../../db/eiger.template", "P=17EIG1:,R=cam1:,PORT=EIG,ADDR=0,TIMEOUT=1")
Can't set "17EIG1:cam1:FWNamePattern.VAL" to "series_$id"
Error at or before ")" in file "/path/to/ADEiger/iocs/eigerIOC/../../db/eiger.template" line 262
```

That record instance looks like this:

```
record(waveform, "$(P)$(R)FWNamePattern") {
    field(PINI, "YES")
    field(DTYP, "asynOctetWrite")
    field(INP,  "@asyn($(PORT),$(ADDR),$(TIMEOUT))NAME_PATTERN")
    field(FTVL, "CHAR")
    field(NELM, "256")
    field(VAL,  "series_$id")
    info(autosaveFields, "VAL")
}
```

Based on the [EPICS 7 release notes](https://epics.anl.gov/base/R7-0/3-docs/RELEASE_NOTES.html) in section "Changes made between 3.16.0.1 and 3.16.1," subsection "Constant Link Values," I'm guessing that support for initializing the `VAL` field with a constant string like this is only supported in EPICS 3.16.1 and newer.  (I'm not sure because the text there says "an array containing a single string value can also be used to initialize scalar strings, so . . . waveform . . . record types and/or their soft device supports have been modified to support this."  In this case, it's not a string inside an array, so I'm not exactly sure how it works, but maybe it's covered in the documentation.)

So, I removed the `VAL` line

```
    field(VAL,  "series_$id")
```

and then `eiger.template` loads successfully without an error.

**Comment by MarkRivers** [comment]
In commit 85f9c40f96995a95af6166093a6301ca6aacc484 I changed the record type of FWNamePattern from stringout to waveform, so it could hold longer strings.  I should have removed the VAL field at that point.  It will now need to be initialized with autosave or dbpf at the end of st.cmd

**Comment by jlmuir** [comment]
OK, thanks!  Do you want to fix that, or should I submit a PR for it?

**Comment by MarkRivers** [comment]
Oh darn, I did not look closely at this PR before I merged it.  I thought it was your change to delete the VAL field, but it was actually a big change for the Eiger2.  

I just reverted my merge.

@jlmuir can you issue a PR for the VAL field issue?

@GDYendell can you issue a new PR for WIP: 1.8?

**Comment by jlmuir** [comment]
> @jlmuir can you issue a PR for the VAL field issue?

Will do shortly.  BTW, it looks like the stringout-to-waveform change was actually 6bcec7c.

**Comment by jlmuir** [comment]
Hmm, do you want it to be initialized with `dbpf` in `st.cmd`?  The downside is of course that the `dbpf` would overwrite anything restored by autosave.

**Comment by jlmuir** [comment]
Why are various record instances in `eiger.template` commented out?

I'm seeing various PVs as white rectangles (i.e., not connected) in the `eigerDetector.adl` MEDM screen.  For example, `$(P)$(R)Wavelength` is not connected:

eiger-wavelength

This is because it's commented out in `eiger.template`:

```
#record(ao, "$(P)$(R)Wavelength")
#{
#    field(DTYP, "asynFloat64")
#    field(OUT,  "@asyn($(PORT),$(ADDR),$(TIMEOUT))WAVELENGTH")
#    field(PREC, "4")
#    field(EGU,  "Angstroms")
#}
```

**Comment by MarkRivers** [comment]
They were presumably commented out because they are not supported on the Eiger2, and the medm screen have not been modified to match the template file.

We need to decide how to handle both Eiger1 and Eiger2 in this repository.  I would like to avoid have 2 versions of the template, C++, and OPI files if possible.

**Comment by MarkRivers** [comment]
> Hmm, do you want it to be initialized with dbpf in st.cmd? The downside is of course that the dbpf would overwrite anything restored by autosave.

I would prefer to document the use of ```series_$id``` and then use autosave to restore it.

**Comment by GDYendell** [comment]
Created #30 .

**Comment by jlmuir** [comment]
>> Hmm, do you want it to be initialized with dbpf in st.cmd? The downside is of course that the dbpf would overwrite anything restored by autosave.

> I would prefer to document the use of series_$id and then use autosave to restore it.

The more I think about this, the more I'm not sure of the best way to do it.  If it doesn't get set automatically, then it will be a special step that any user would have to do the first time they start using the driver (e.g., run this `dbpf` or `caput` command, or open this MEDM screen and type in this value).  That feels like a bad user experience to me.

Other ideas:

* Put `dbpf("$(PREFIX)cam1:FWNamePattern", "series_$id")` at the end of `st.cmd` with a comment to remove it after the IOC has been started once.  Seems not so good.  But I guess if there's a user instruction step to edit `st.cmd` to change `PREFIX`, then there could be another step to do this.
* Supply an autosave file in the `autosave` directory with the desired `series_$id` value?  That way, when the IOC starts for the first time, autosave will restore that value?  But I think this won't work because autosave doesn't save PV names with macros in them; all the PV names are literals.  So, if a user changes the `PREFIX` environment variable, autosave won't be able to restore the value.
* Set `PINI` to `NO` for the `$(P)$(R)FWNamePattern` record instance and just read the default from the DCU.  I tried this, and it doesn't work; the default seems to be the empty string.  Not sure what's going on here since the EIGER2 SIMPLON API doc says that the default is `series_$id`.
* Set the default in `eigerDetector::initParams()`.  Will this be called before autosave?  If yes, then I think it should work, but I don't know when autosave does its thing.  (Actually, I think I remember something about autosave having two passes that it does.)

**Comment by GDYendell** [comment]
All,

I have now completely replaced this branch with a version that is compatible with Eiger1 and Eiger2 detectors. This is now a WIP, as the name suggests. I have not tested this against a real detector yet. 

**If you wish to use the original branch that you pulled from here, I duplicated it to dls-controls/eiger2, so you can use that.**

Please see my latest comment on #30 for more information.

**Pull request merged**
