### PR TITLE
WIP: Update to work with both 1.6 and 1.8 SIMPLON API

### PR DESCRIPTION
**Pull request by GDYendell**

### CODE REVIEW

**Comment by jlmuir** [comment]
@GDYendell, so this is not the same as WIP 1.8 PR #27.  It appears to be what you referred to in your [PR #27 comment on 2019-12-06](https://github.com/areaDetector/ADEiger/pull/27#issuecomment-562533870) where you said (referring to the driver working with an EIGER or EIGER2):

> There is further work required to make ADEiger work happily with both so that this can be merged. I do have a local branch with some progress towards this, but the current state is that it doesn't work with either. I haven't pushed it here as then there would not be any Eiger2 solution available.

So, is this the state of this PR: it doesn't work with either?

**Comment by GDYendell** [comment]
No, this branch is still just master with new things exposed and missing things commented out. It should work for only Eiger2. It is rebased on the latest master, though, so there are some OPI changes, I think.

Sorry if the title of this PR is confusing. That is just what I think it should be by the time it is merged.

**Comment by jlmuir** [comment]
Got it!  I was just in the middle of writing a comment to say that I realized that the PR commits were the same.  Sorry.  What's changed is the `dls-controls:1.8` branch.  But as you said, you rebased, so that would explain why I saw changes today compared to yesterday.

**Comment by GDYendell** [comment]
All,

I have now completely replaced this branch with a version that is compatible with Eiger1 and Eiger2 detectors. This is now a WIP, as the name suggests. I have not tested this against a real detector yet. 

**If you wish to use the original branch that you pull from here, I duplicated it to dls-controls/eiger2, so you can use that.**

The main difference between this and the original branch is the template has been split into eiger1 and eiger2, so one of those should be instantiated. There are more parameters in both (Eiger1 now supports bit depth image and Eiger2 has now regained some more lost parameters). The logic in the code now has a few if cases throughout to support both models.

This includes the fix to remove the VAL field on FWNamePattern, as discussed on the previous PR. This is kind of unrelated, but I couldn't run my test IOC without the fix.

This also adds an LZ4 macro that should be defined in configure/CONFIG_SITE* to enable use of external (non-ADSupport) builds of lz4 and bitshuffle.

**Comment by jlmuir** [comment]
With my DCU running the EIGER2 2020.1 release, the first time I start the ADEiger IOC after initializing the detector I get messages on the console like this:

```
2020-07-07 13:07:28.014446645  iocInit()
2020-07-07 13:07:28.014447418  Starting iocInit
2020-07-07 13:07:28.014448214  ############################################################################
2020-07-07 13:07:28.014448914  ## EPICS R3.15.7
2020-07-07 13:07:28.014449631  ## EPICS Base built Dec 18 2019
2020-07-07 13:07:28.014450401  ############################################################################
2020-07-07 13:07:28.044323492  2020/07/07 13:07:28.044 Param[EIG_DCD_chi_start]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.045584445  2020/07/07 13:07:28.046 Param[EIG_DCD_chi_increment]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.047953009  2020/07/07 13:07:28.048 Param[EIG_DCD_kappa_start]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.049290647  2020/07/07 13:07:28.049 Param[EIG_DCD_kappa_increment]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.050577271  2020/07/07 13:07:28.051 Param[EIG_DCD_omega_start]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.051731029  2020/07/07 13:07:28.052 Param[EIG_DCD_omega_increment]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.052876759  2020/07/07 13:07:28.053 Param[EIG_DCD_phi_start]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.054139121  2020/07/07 13:07:28.054 Param[EIG_DCD_phi_increment]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.055416634  2020/07/07 13:07:28.055 Param[EIG_DCD_two_theta_start]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.056617442  2020/07/07 13:07:28.057 Param[EIG_DCD_two_theta_increment]::parseValue: couldn't parse value 'null' as double
2020-07-07 13:07:28.615992317  iocRun: All initialization complete
```

So, it seems that the SIMPLON API resets certain parameters to `null` when the detector is initialized.  According to DECTRIS, this is by design.  Subsequent starts of the ADEiger IOC do not produce these error messages, so I assume the EPICS records with `PINI=YES` have caused the parameters to be set to default values.  This is all *without* using `autosave`, BTW.

What would be a good way to handle this?  Just leave it as is?  Always set those parameters to default values at IOC start in `eigerDetector::initParams(void)` before calling `mParams.fetchAll()`?  Modify `EigerParamSet::fetchAll(void)` to accept an "exclude list" of parameters to *not* fetch, therefore not triggering the error messages?  Change the `parseValue` methods to treat `null` as `false`, `0`, and `0.0`?  (This one is my least favorite; probably not a good idea.)

**Comment by GDYendell** [comment]
As these parameters are created dynamically from the asyn parameter name, I think these errors might be coming from here https://github.com/areaDetector/ADEiger/blob/master/eigerApp/src/eigerDetector.cpp#L1738 rather than the fetchAll in the constructor.

**Comment by jlmuir** [comment]
Ah, I see.  Sorry, you're probably right.  My question of how best to get rid of these error messages still stands.

**Comment by GDYendell** [comment]
I agree it is probably not a good idea to assume `null` means `0`, `0.0`, `false` etc, but `fetch`/`parseValue` could be updated to give a slightly more useful and more benign looking error if it gets `null`, or perhaps just a TRACE level message. Do we know if `null` is also used to indicate any kind of error state?

**Comment by jlmuir** [comment]
> Do we know if null is also used to indicate any kind of error state?

I don't know.

**Comment by jlmuir** [comment]
Extend the `drvInfo` string to support supplying a default value to be used if no value is set (i.e., API JSON `null`) and pass it, if supplied, to the `fetch` function as a default value?

Right now, the format is `EIG_XYZ_name`, and it could be changed to `EIG_XYZA_name` where `A` would be `T` for `true` if `name` begins with a default value followed by an underscore character, and `F` for `false` if not.  With this scheme, either the default value would not be allowed to contain an underscore character (I'm thinking for the case where `Z` is `S` [`asynOctet`]) or we'd have to support escaping it.  I'd be in favor of supporting escaping it by preceding it with another underscore.

Ideally we could just grab the default value from the record's `VAL` field, but I don't even know if that's possible, so I just put it in the `drvInfo` string.

Also, I don't know much about the `drvInfo` string.  Is it possible to put more arguments in the EPICS record `INP` or `OUT` field `@asyn(<args>)` part and get access to that from the `drvUserCreate` function?  That would probably be a better way to specify a default value, but if that's the case, then it seems like the ADEiger driver should have used that mechanism rather than encoding the information in the `EIG_XYZ_name` format.

On a side note, if the `@asyn(<args>)` part were extended to accept a default value, then maybe that could become a general-purpose default-value mechanism built into Asyn.

Anyway, here's an example of the idea for the `chi_start` API parameter in `eigerBase.template` (I'm not even sure whether the fetch is coming from the `ao` or `ai` record, but I'll guess it's from the `ao` record, so that's what's shown here):

```
record(ao, "$(P)$(R)ChiStart")
{
    field(PINI, "YES")
    field(DTYP, "asynFloat64")
    field(OUT,  "@asyn($(PORT),$(ADDR),$(TIMEOUT))EIG_DCDT_0.0_chi_start")
    field(PREC, "3")
    field(EGU,  "deg")
}
```

**Comment by jlmuir** [comment]
> As these parameters are created dynamically from the asyn parameter name, I think these errors might be coming from here https://github.com/areaDetector/ADEiger/blob/master/eigerApp/src/eigerDetector.cpp#L1738 rather than the fetchAll in the constructor.

Why does `eigerDetector::drvUserCreate` even do a fetch?  I'm wondering if it should *not* do that and instead the fetch should only be done if a read is requested.

**Comment by GDYendell** [comment]
It would be much nicer if we could access VAL for a default value, than to add more to the `drvInfo` string. I don't know if that is possible. Maybe one for techtalk? Even then, I don't think it makes sense for `fetch` to take a default value, which would then presumably require a `put`. `fetch` shouldn't change the state of the detector. Maybe if it checked for it and then didn't do the `fetch` at all.

I think it does make sense, conceptually at least, to fetch these parameters once when they are created. They are not polled because of the mechanism of PUTs returning changed values to update afterwards, so they would never be fetched until they, or something related, was set. Also, I think some absolutely depend on it, e.g. SensorThickness. That might be the only place it is fetched, because it never changes.

I think if DECTRIS say this is the API, then the driver should understand it and do whatever makes most sense, which is probably to not update the value but also not log it as an error. By receiving `null` I guess we know at least that the parameters can be accessed and that any `put`s will be successful.

I also wonder, if these parameters are returning `null`, what will then come out on the global header (which includes these)? Will that also be `null`? Or maybe the act of running the acquisition will set them to a useful default, like 0.

**Comment by jlmuir** [comment]
> It would be much nicer if we could access VAL for a default value, than to add more to the `drvInfo` string. I don't know if that is possible. Maybe one for techtalk?

@MarkRivers will know.  Mark, is this possible with Asyn?

**Comment by jlmuir** [comment]
> Even then, I don't think it makes sense for `fetch` to take a default value, which would then presumably require a `put`. `fetch` shouldn't change the state of the detector. Maybe if it checked for it and then didn't do the `fetch` at all. Or maybe if there is a `VAL` and `PINI=YES` then that means we should do a `put` instead of a `fetch`.

Not sure what you mean.  I don't think `fetch` taking a default value would mean that it requires a `put`.  The behavior would be that `fetch` would "return" (i.e., use) the specified default value if the value read from the API is `null`.  This would be analogous to getter methods on hash-table-like objects in various languages that take a default value: if the key does not exist, the default value is returned.  For example:

* [Ruby's `Hash#fetch(key[, default])`](https://ruby-doc.org/core-2.7.1/Hash.html#method-i-fetch)
* [Python's `dict#get(key[, default])`](https://docs.python.org/3/library/stdtypes.html#mapping-types-dict)
* [Java's `Map#getOrDefault(key, defaultValue)`](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#getOrDefault-java.lang.Object-V-)

**Comment by MarkRivers** [comment]
I think that what you are discussing can perhaps already be done using the standard features of asyn for bumpless reboot.  Consider the record that @jlmuir listed above but without a default in the drvUser field.
```
record(ao, "$(P)$(R)ChiStart")
{
    field(PINI, "YES")
    field(DTYP, "asynFloat64")
    field(OUT,  "@asyn($(PORT),$(ADDR),$(TIMEOUT))EIG_DCDT_chi_start")
    field(PREC, "3")
    field(EGU,  "deg")
}
```

In the standard asyn ao device support it does the following:
- Calls pasynFloat64SyncIO->read() with the pasynUser attached to that record (and hence that drvUser field).
- If that read returns asynSuccess it puts the returned value in the VAL field.
- If that read does not return asynSuccess it leaves the VAL field unchanged.

Hence all the driver needs to do is return failure on that read to have the VAL field be the default.

The simplest way to ensure that the read returns failure is not call call setDoubleParam on that parameter if the fetch in drvUserCreate() does not return a valid value.  The asynPortDriver base class readFloat64 method will then see that the value has never been written and return asynError.

Because the record also has PINI=YES the default value in the VAL field will then be written to the device later in iocInit.

**Comment by jlmuir** [comment]
> > Do we know if `null` is also used to indicate any kind of error state?
> 
> I don't know. I'll ask DECTRIS.

DECTRIS said that the developers that know for sure are out of the office, but their understanding is as follows:

> Values will not be changed if they are set out of bounds, and any error state should have a value and appropriate flag as error, we do not set parameter values to null to indicate an error state.

So, I would take that to mean that it's safe for ADEiger to interpret `null` to mean "no value set."

**Comment by GDYendell** [comment]
That sounds like it will do what we want if we just check for `null` as an accepted failure mode and return before setDoubleParam. Do we need to add VAL=0 to these records, or is that the default?

**Comment by cmkewish** [comment]
Hi @GDYendell - I have installed this pull #30 today to use with release_2020.1 installed today for our EIGER2 X 1M detector. I had to just customise `st.cmd` file to include our standard PV PREFIX, our EIGERIP and the XSIZE and YSIZE, and then the bits which held me up for a while were:
`eigerDetectorConfig("$(PORT)", "$(EIGERIP)", 2, 0)` <--  '2' for detector identifier instead of a '0'
and:
`dbLoadRecords("$(ADEIGER)/db/eigerBase.template", "P=$(PREFIX),R=cam1:,PORT=$(PORT),ADDR=0,TIMEOUT=1")` in lieu of 'eiger.template'
I admit that I don't use much of the areaDetector functionality besides serving PVs to our control system, but I'm happy to try and run any tests.

**Comment by MarkRivers** [comment]
> Do we need to add VAL=0 to these records, or is that the default?

I believe VAL=0 is the default for all records where VAL is numeric.

**Comment by GDYendell** [comment]
@cmkewish At DLS we don't make use of the example IOC, so I overlooked updating it. If you can confirm the correct changes we can either do a PR into this branch or I can just cherry-pick the commits if you point me to a branch. The only thing I would note is that you should load either the eiger1.template or eiger2.template, which both include eigerBase.template and override/add PVs that are specific to that model. For example, if you load eigerBase.template for an Eiger2, there will be some missing PVs and some enums will be in the wrong order.

**Comment by cmkewish** [comment]
@GDYendell Noted, thanks I've made that change from `eigerBase.template` to `eiger2.template` - I had to also put the full path to `eigerBase.template` inside the `eiger2.template` file as it was not able to find it without, but perhaps that's a configuration issue on my side. 

The IOC throws a bit of this sort of thing as mentioned above, but otherwise looks like it's giving me the right PVs:
`2020/07/22 13:21:19.963 Param[EIG_DCD_chi_increment]::parseValue: couldn't parse value 'null' as double
...`

**Comment by MarkRivers** [comment]
> I had to also put the full path to eigerBase.template inside the eiger2.template file as it was not able to find it without, but perhaps that's a configuration issue on my side.

You need to add the directory containing eigerBase.template in your EPICS_DB_INCLUDE_PATH environment variable in your startup script.
```
epicsEnvSet("EPICS_DB_INCLUDE_PATH", "$(ADCORE)/db:$(ADEIGER)/db")
```
```

**Comment by GDYendell** [comment]
We have recently had a new Eiger2 and an update on one of our Eiger2 detectors and they both have changed the order of the allowed values for TriggerMode (with no change to the firmware version). Now some have 

```
0 | "ints"
1 | "exte"
2 | "inte"
3 | "exts"
```

and others say

```
0 | "ints"
1 | "exts"
2 | "inte"
3 | "exte"
```

which is difficult to work around with the mbbi enum values being defined at startup. I think we will be raising this with Dectris as I don't see why they cannot just retain the order from 1.6.0 for all detectors. Has anyone else seen this or perhaps even have another different order?

**Comment by cmkewish** [comment]
Hi @GDYendell - in the Dectris SIMPLON API 1.8.0 v2.0 documentation (2020-07-17), the `trigger_mode` URL expects a string. I think it's always been this way in the RESTful interface, leaving us free to define the enumerated order as we like in any control software sending the requests.

```
$curl -X GET http://eigerdcuIP/detector/api/1.8.0/config/trigger_mode
{"access_mode":"rw","allowed_values":["exte","exts","inte","ints"],"value":"ints","value_type":"string"}
```

**Comment by GDYendell** [comment]
@cmkewish that is true. I think that because the mTriggerMode parameter in the driver is defined as an int, any PUTs send the integer representation. Maybe if it was a string instead it would send the string value directly.

**Comment by jlmuir** [comment]
> We have recently had a new Eiger2 and an update on one of our Eiger2 detectors and they both have changed the order of the allowed values for TriggerMode (with no change to the firmware version). Now some have
> 
> [snip]
> 
> which is difficult to work around with the mbbi enum values being defined at startup. I think we will be raising this with Dectris as I don't see why they cannot just retain the order from 1.6.0 for all detectors, or at least stick with one for 1.8.0. Has anyone else seen this or perhaps even have another different order?

DECTRIS breaks API backward compatibility of their versioned APIs.  It's very frustrating.  I have raised this as an issue on its own with them as well.  BTW, another example of an ordering change and fix is commit [694b14f](https://github.com/dls-controls/ADEiger/pull/1/commits/694b14ff3a9c84d44f46ca9ffbe597c0436d97d5) from the [Fix 1.8 issues after EIGER2 2020.1 upgrade PR](https://github.com/dls-controls/ADEiger/pull/1) against the 1.8 branch.

**Comment by MarkRivers** [comment]
If the driver implemented the asynEnum interface for enum fields the mbbi records would have the choices and  order that the device uses, rather  than hard coded in the database. Look at ADGenICam for an example.

**Comment by MarkRivers** [comment]
@GDYendell I plan to make time in the next few weeks to make ADEiger work with both the Eiger and Eiger2 detectors.  I also plan to add support for the new features of the Eiger2, such as dual thresholds, etc.  I should have both an older Eiger500 and a new Eiger2X available for testing.

Of course I want to avoid duplicating anything that you or others may have already done.  Is this PR the best place to start, or do you have another branch that I should use instead?

**Comment by GDYendell** [comment]
This is the most up to date branch. The only thing is I will rebase it on master as some changes have been made there and it is confusing. For example the lines mentioned here https://epics.anl.gov/tech-talk/2020/msg02134.php were removed from master since this branch, so now it looks this branch adds them.

One related thing; Dectris have agreed to start providing release notes with each detector firmware version. This can be found in the usual docs location for each detector type (e.g. https://www.dectris.com/support/manuals-docs/eiger2-x-and-xe-cdte-synchrotron/eiger2-xe-cdte-16m/), but they all open the same link.

We have also received a more up to date version by email that they have not yet uploaded. One thing of note is the addition of the list parameter type has been removed, as it was considered a bug. This branch was updated to add support for the list type in e72262. So, possibly this should be removed and we should recommend to upgrade to firmware 2020.2 and skip 2020.1.

**Comment by GDYendell** [comment]
Also, re: https://epics.anl.gov/tech-talk/2020/msg02139.php, I think I added a09acc to get it to build against bitshuffle and lz4 from ADSupport, possibly using BITSHUFFLE_EXTERNAL=YES, but maybe I was going about this the wrong way. I don't use this in the DLS build.

**Comment by MarkRivers** [comment]
I have taken the dka-controls:1.8 branch and moved it to the 1.6_and_1.8 branch in this repository.  I will work on testing it with both Eiger1 and Eiger2 detectors.  I will also add new PVs to control Eiger2 features like dual-thresholds that are not currently exposed in EPICS.  Once that is complete I will merge into master.

**Pull request closed without merging**
